version: 7.0.4.{build}

image: Visual Studio 2019
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

before_build:
  - dotnet restore

build:
  project: src/Elasticsearch.Net.Aws/Elasticsearch.Net.Aws.sln

artifacts:
  - path: '**\*.nupkg'
    name: NuGet