version: 7.0.4.{build}

image: Visual Studio 2019
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

before_build:
  - dotnet restore src/Elasticsearch.Net.Aws/Elasticsearch.Net.Aws.sln

build_script:
  - dotnet build src/Elasticsearch.Net.Aws/Elasticsearch.Net.Aws.sln

test_script:
  - dotnet test src/Elasticsearch.Net.Aws/ElasticSearch.Net.Aws.Tests/ElasticSearch.Net.Aws.Tests.csproj

artifacts:
  - path: '**\*.nupkg'
    name: NuGet